---
# Add tasks to update and upgrade the system here
# Add tasks to install packages such as python3 and nginx here
# Use a defaults/main.yml file to define package names and/or versions if necessary
# Use a handlers/main.yml file to enable and start nginx
- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
  tags: prerequisites

- name: Install required packages
  apt:
    name: "{{ item.name }}"
    state: present
  loop: "{{ packages }}"
  tags: prerequisites

- name: Install and notify for Nginx
  apt:
    name: nginx
    state: present
  notify: Enable and start Nginx
  tags: prerequisites
