services:
  webserver:
    build:
      context: .
      dockerfile: bin/webserver/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./webroot:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-available
      - ./logs/apache2:/var/log/apache2
    container_name: webserver
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"

  db:
    image: mysql:8.0  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}       
      MYSQL_USER: ${MYSQL_USER}               
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}       
    volumes:   
      - ./data/mysql:/var/lib/mysql      
      - ./logs/mysql:/var/log/mysql      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=db  
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
